const firstNames = [
    "Liam",
    "Olivia",
    "Noah",
    "Emma",
    "Oliver",
    "Ava",
    "Elijah",
    "Sophia",
    "William",
    "Isabella",
    "James",
    "Mia",
    "Benjamin",
    "Charlotte",
    "Lucas",
    "Amelia",
    "Henry",
    "Harper",
    "Alexander",
    "Evelyn",
    "Michael",
    "Abigail",
    "Daniel",
    "Emily",
    "Matthew",
    "Elizabeth",
    "Ethan",
    "Mila",
    "Joseph",
    "Ella",
    "David",
    "Avery",
    "Jackson",
    "Scarlett",
    "Sebastian",
    "Grace",
    "Carter",
    "Chloe",
    "Samuel",
    "Luna",
    "Josephine",
    "Mateo",
    "Riley",
    "Lillian",
    "Levi",
    "Zoey",
    "Dylan",
    "Penelope",
    "Nathan",
    "Nora",
    "Emily",
    "Madison",
    "Leo",
    "Layla",
    "Mila",
    "Eleanor",
    "Hudson",
    "Hannah",
    "Daniel",
    "Lily",
    "Eli",
    "Addison",
    "Landon",
    "Aubrey",
    "Jonathan",
    "Stella",
    "Natalie",
    "Gabriel",
    "Aria",
    "Sofia",
    "Lucas",
    "Alexa",
    "Aaron",
    "Camila",
    "Eleanor",
    "Maya",
    "Hunter",
    "Nevaeh",
    "Christian",
    "Violet",
    "Ariana",
    "Grayson",
    "Savannah",
    "Eva",
    "Emilia",
    "Isaac",
    "Hazel",
    "Isabelle",
    "Thomas",
    "Audrey",
    "Ezra",
    "Claire",
    "Brooklyn",
    "Bella",
    "Nova",
    "Genesis",
    "Elizabeth",
    "Kinsley",
    "Aurora",
    "Leah",
    "Naomi",
    "Maya",
    "Valentina",
    "Lucy",
    "Brielle",
    "Sarah",
    "Kennedy",
    "Elena",
    "Rylee",
    "Adeline",
    "Jasmine",
    "Aaliyah",
    "Arianna",
    "Charlie",
    "Ryleigh",
    "Liliana",
    "Andrea",
    "Kaylee",
    "Aubree",
    "Daisy",
    "Annabelle",
    "Lyla",
    "Willow",
    "Melanie",
    "Mila",
    "Londyn",
    "Lydia",
    "Samantha",
    "Caroline",
    "Violet",
    "Stella",
    "Nova",
    "Hannah",
    "Gianna",
    "Taylor",
    "Layla",
    "Alexa",
    "Zoe",
    "Penelope",
    "Riley",
    "Nora",
    "Leah",
    "Aria",
    "Hazel",
    "Aaliyah",
    "Skylar",
    "Ellie",
    "Bella",
    "Natalie",
    "Lily",
    "Luna",
    "Lucy",
    "Ariana",
    "Corinne",
    "Faith",
    "Isabelle",
    "Rose",
    "Makenna",
    "Eliana",
    "Melody",
    "Remi",
    "Josie",
    "Ivy",
    "Nina",
    "Emerson",
    "Zara",
    "Piper",
    "Lola",
    "Teagan",
    "Adeline",
    "Athena",
    "Astrid",
    "Everly",
    "Catalina",
    "Gabriela",
    "Mariana",
    "Delilah",
    "Vivienne",
    "Kylie",
    "Clara",
    "Raegan",
    "Camille",
    "Brynn",
    "Reese",
    "Elise",
    "Hope",
    "Sienna",
    "Alaina",
    "Myla",
    "Isla",
    "Quinn",
    "Lyric",
    "Rylie",
    "Hayden",
    "Harmony",
    "Lena",
    "Holly",
    "Juliette",
    "Kiara",
    "Daleyza",
    "Fatima",
    "Heidi",
    "Lana",
    "Maisie",
    "Noelle",
    "Paige",
    "Selena",
    "Talia",
    "Celeste",
    "Diana",
    "Aileen",
    "Amara",
    "Carmen",
    "Eden",
    "Giselle",
    "Lia",
    "Raven",
    "Wren",
    "Zariah",
    "Amira",
    "April",
    "Cleo",
    "Francesca",
    "Kira",
    "Nola",
    "Shiloh",
    "Ayla",
    "Elaina",
    "Kayleigh",
    "Marley",
    "Zola",
    "Rosalie",
    "Samara",
    "Ainsley",
    "Cassandra",
    "Esme",
    "Harper",
    "Jolie",
    "Kiana",
    "Maeve",
    "Noemi",
    "Sariah",
    "Thalia",
    "Ximena",
  ]

  const lastNames = [
    "Smith",
    "Johnson",
    "Williams",
    "Jones",
    "Brown",
    "Davis",
    "Miller",
    "Wilson",
    "Moore",
    "Taylor",
    "Anderson",
    "Thomas",
    "Jackson",
    "White",
    "Harris",
    "Martin",
    "Thompson",
    "Garcia",
    "Martinez",
    "Robinson",
    "Clark",
    "Rodriguez",
    "Lewis",
    "Lee",
    "Walker",
    "Hall",
    "Allen",
    "Young",
    "Hernandez",
    "King",
    "Wright",
    "Lopez",
    "Hill",
    "Scott",
    "Green",
    "Adams",
    "Baker",
    "Gonzalez",
    "Nelson",
    "Carter",
    "Mitchell",
    "Perez",
    "Roberts",
    "Turner",
    "Phillips",
    "Campbell",
    "Parker",
    "Evans",
    "Edwards",
    "Collins",
    "Stewart",
    "Sanchez",
    "Morris",
    "Rogers",
    "Reed",
    "Cook",
    "Morgan",
    "Bell",
    "Murphy",
    "Bailey",
    "Rivera",
    "Cooper",
    "Richardson",
    "Cox",
    "Howard",
    "Ward",
    "Torres",
    "Peterson",
    "Gray",
    "Ramirez",
    "James",
    "Watson",
    "Brooks",
    "Kelly",
    "Sanders",
    "Price",
    "Bennett",
    "Wood",
    "Barnes",
    "Ross",
    "Henderson",
    "Coleman",
    "Jenkins",
    "Perry",
    "Powell",
    "Long",
    "Patterson",
    "Hughes",
    "Flores",
    "Washington",
    "Butler",
    "Simmons",
    "Foster",
    "Gonzales",
    "Bryant",
    "Alexander",
    "Russell",
    "Griffin",
    "Diaz",
    "Hayes",
    "Myers",
    "Ford",
    "Hamilton",
    "Graham",
    "Sullivan",
    "Wallace",
    "Woods",
    "Cole",
    "West",
    "Jordan",
    "Owens",
    "Reynolds",
    "Fisher",
    "Ellis",
    "Harrison",
    "Gibson",
    "Mcdonald",
    "Cruz",
    "Marshall",
    "Ortiz",
    "Gomez",
    "Murray",
    "Freeman",
    "Wells",
    "Webb",
    "Simpson",
    "Stevens",
    "Tucker",
    "Porter",
    "Hunter",
    "Hicks",
    "Crawford",
    "Henry",
    "Boyd",
    "Mason",
    "Morales",
    "Kennedy",
    "Warren",
    "Dixon",
    "Ramos",
    "Reyes",
    "Burns",
    "Gordon",
    "Shaw",
    "Holmes",
    "Rice",
    "Robertson",
    "Hunt",
    "Black",
    "Daniels",
    "Palmer",
    "Mills",
    "Nichols",
    "Grant",
    "Knight",
    "Ferguson",
    "Rose",
    "Stone",
    "Hawkins",
    "Dunn",
    "Perkins",
    "Hudson",
    "Spencer",
    "Gardner",
    "Stephens",
    "Payne",
    "Pierce",
    "Berry",
    "Matthews",
    "Arnold",
    "Wagner",
    "Willis",
    "Ray",
    "Watkins",
    "Olson",
    "Carroll",
    "Duncan",
    "Snyder",
    "Hart",
    "Cunningham",
    "Bradley",
    "Lane",
    "Andrews",
    "Ruiz",
    "Harper",
    "Fox",
    "Riley",
    "Armstrong",
    "Carpenter",
    "Weaver",
    "Greene",
    "Lawrence",
    "Elliott",
    "Chavez",
    "Sims",
    "Austin",
    "Peters",
    "Kelley",
    "Franklin",
    "Lawson",
    "Fields",
    "Gutierrez",
    "Ryan",
    "Schmidt",
    "Carr",
    "Vasquez",
    "Castillo",
    "Wheeler",
    "Chapman",
    "Oliver",
    "Montgomery",
    "Richards",
    "Williamson",
    "Johnston",
    "Banks",
    "Meyer",
    "Bishop",
    "Mccoy",
    "Howell",
    "Alvarez",
    "Morrison",
    "Hansen",
    "Fernandez",
    "Garza",
    "Harvey",
    "Little",
    "Burton",
    "Stanley",
    "Nguyen",
    "George",
  ]

  const animalNames = [
    "Tiger",
    "Lion",
    "Elephant",
    "Giraffe",
    "Zebra",
    "Monkey",
    "Kangaroo",
    "Koala",
    "Panda",
    "Hippo",
    "Gorilla",
    "Cheetah",
    "Leopard",
    "Penguin",
    "Koala",
    "Kangaroo",
    "Crocodile",
    "Alligator",
    "Giraffe",
    "Jaguar",
    "Koala",
    "Llama",
    "Meerkat",
    "Ostrich",
    "Penguin",
    "Polar Bear",
    "Raccoon",
    "Sloth",
    "Turtle",
    "Wolf",
    "Zebra",
    "Aardvark",
    "Alpaca",
    "Baboon",
    "Bat",
    "Bear",
    "Beaver",
    "Bison",
    "Camel",
    "Chimpanzee",
    "Chinchilla",
    "Chipmunk",
    "Cougar",
    "Coyote",
    "Deer",
    "Dolphin",
    "Duck",
    "Eagle",
    "Falcon",
    "Fennec Fox",
    "Flamingo",
    "Fox",
    "Gazelle",
    "Gorilla",
    "Grizzly Bear",
    "Hamster",
    "Hedgehog",
    "Hippo",
    "Hyena",
    "Iguana",
    "Jaguar",
    "Kangaroo Rat",
    "Koala",
    "Lemur",
    "Lion",
    "Lizard",
    "Lynx",
    "Manatee",
    "Meerkat",
    "Mongoose",
    "Monkey",
    "Ocelot",
    "Orangutan",
    "Otter",
    "Panda",
    "Penguin",
    "Platypus",
    "Polar Bear",
    "Porcupine",
    "Puma",
    "Rabbit",
    "Raccoon",
    "Red Panda",
    "Reindeer",
    "Seal",
    "Sloth",
    "Snake",
    "Squirrel",
    "Tasmanian Devil",
    "Tiger",
    "Toucan",
    "Turtle",
    "Walrus",
    "Wolf",
    "Wombat",
    "Yak",
    "Zebra",
    "Armadillo",
    "Bison",
    "Cheetah",
    "Chameleon",
    "Dolphin",
    "Eagle",
    "Falcon",
    "Giraffe",
    "Gorilla",
    "Hedgehog",
    "Hummingbird",
    "Jaguar",
    "Kangaroo",
    "Koala",
    "Lion",
    "Llama",
    "Meerkat",
    "Narwhal",
    "Ocelot",
    "Panda",
    "Penguin",
    "Polar Bear",
    "Quokka",
    "Raccoon",
    "Red Panda",
    "Sloth",
    "Toucan",
    "Umbrellabird",
    "Vampire Bat",
    "Walrus",
    "X-ray Tetra",
    "Yak",
    "Zebra",
    "Aardvark",
    "Baboon",
    "Cheetah",
    "Chimpanzee",
    "Dolphin",
    "Elephant",
    "Flamingo",
    "Giraffe",
    "Gorilla",
    "Hippopotamus",
    "Iguana",
    "Jaguar",
    "Kangaroo",
    "Lemur",
    "Lion",
    "Meerkat",
    "Narwhal",
    "Ocelot",
    "Penguin",
    "Polar Bear",
    "Quokka",
    "Raccoon",
    "Sloth",
    "Turtle",
    "Umbrellabird",
    "Vulture",
    "Walrus",
    "X-ray Tetra",
    "Yak",
    "Zebra",
  ];
  
  const colors = [
    "Aqua",
    "Aquamarine",
    "Azure",
    "Beige",
    "Bisque",
    "Black",
    "Blue",
    "Brown",
    "Burlywood",
    "CadetBlue",
    "Chartreuse",
    "Chocolate",
    "Coral",
    "CornflowerBlue",
    "Crimson",
    "Cyan",
    "DarkBlue",
    "DarkCyan",
    "DarkGoldenrod",
    "DarkGray",
    "DarkGreen",
    "DarkKhaki",
    "DarkMagenta",
    "DarkOliveGreen",
    "DarkOrange",
    "DarkOrchid",
    "DarkRed",
    "DarkSalmon",
    "DarkSeaGreen",
    "DarkSlateBlue",
    "DarkSlateGray",
    "DarkTurquoise",
    "DarkViolet",
    "DeepPink",
    "DeepSkyBlue",
    "DimGray",
    "DodgerBlue",
    "FireBrick",
    "ForestGreen",
    "Fuchsia",
    "Gold",
    "Goldenrod",
    "Gray",
    "Green",
    "GreenYellow",
    "HotPink",
    "IndianRed",
    "Indigo",
    "Khaki",
    "Lavender",
    "LawnGreen",
    "LemonChiffon",
    "LightBlue",
    "LightCoral",
    "LightCyan",
    "LightGoldenrodYellow",
    "LightGreen",
    "LightGrey",
    "LightPink",
    "LightSalmon",
    "LightSeaGreen",
    "LightSkyBlue",
    "LightSlateGray",
    "LightSteelBlue",
    "LightYellow",
    "Lime",
    "LimeGreen",
    "Magenta",
    "Maroon",
    "MediumAquamarine",
    "MediumBlue",
    "MediumOrchid",
    "MediumPurple",
    "MediumSeaGreen",
    "MediumSlateBlue",
    "MediumSpringGreen",
    "MediumTurquoise",
    "MediumVioletRed",
    "MidnightBlue",
    "MistyRose",
    "Moccasin",
    "NavajoWhite",
    "Navy",
    "OldLace",
    "Olive",
    "OliveDrab",
    "Orange",
    "OrangeRed",
    "Orchid",
    "PaleGoldenrod",
    "PaleGreen",
    "PaleTurquoise",
    "PaleVioletRed",
    "PapayaWhip",
    "PeachPuff",
    "Peru",
    "Pink",
    "Plum",
    "PowderBlue",
    "Purple",
    "RebeccaPurple",
    "Red",
    "RosyBrown",
    "RoyalBlue",
    "SaddleBrown",
    "Salmon",
    "SandyBrown",
    "SeaGreen",
    "SeaShell",
    "Sienna",
    "Silver",
    "SkyBlue",
    "SlateBlue",
    "SlateGray",
    "Snow",
    "SpringGreen",
    "SteelBlue",
    "Tan",
    "Teal",
    "Thistle",
    "Tomato",
    "Turquoise",
    "Violet",
    "Wheat",
    "White",
    "WhiteSmoke",
    "Yellow",
    "YellowGreen",
    "Crimson",
    "Teal",
    "Sienna",
    "Fuchsia",
    "Indigo",
    "SlateBlue",
    "Violet",
    "Chocolate",
    "Silver",
    "Coral",
    "Khaki",
    "DarkOliveGreen",
    "Cyan",
    "Purple",
    "Blue",
    "Gold",
    "SaddleBrown",
    "Lime",
    "DarkSlateGray",
    "Lavender",
    "Crimson",
    "DarkTurquoise",
    "Olive",
    "DodgerBlue",
    "Red",
    "DeepPink",
    "BlueViolet",
    "MediumVioletRed",
    "DarkViolet",
    "IndianRed",
    "OrangeRed",
    "FireBrick",
    "Coral",
    "Yellow",
    "Gray",
    "Purple",
    "Magenta",
    "LimeGreen",
    "DarkOliveGreen",
    "DarkOrange",
    "Goldenrod",
    "Blue",
    "DodgerBlue",
    "Yellow",
    "Red",
    "Crimson",
    "Teal",
    "Sienna",
    "Fuchsia",
    "Indigo",
    "SlateBlue",
    "Violet",
    "Chocolate",
    "Silver",
    "Coral",
    "Khaki",
    "DarkOliveGreen",
    "Cyan",
    "Purple",
    "Blue",
    "Gold",
    "SaddleBrown",
    "Lime",
    "DarkSlateGray",
    "Lavender",
    "Crimson",
    "DarkTurquoise",
    "Olive",
    "DodgerBlue",
    "Red",
    "DeepPink",
    "BlueViolet",
    "MediumVioletRed",
    "DarkViolet",
    "IndianRed",
    "OrangeRed",
    "FireBrick",
    "Coral",
    "Yellow",
    "Gray",
    "Purple",
    "Magenta",
    "LimeGreen",
    "DarkOliveGreen",
    "DarkOrange",
    "Goldenrod",
  ];

  const countries = [
    { country: "Afghanistan", capital: "Kabul" },
    { country: "Albania", capital: "Tirana" },
    { country: "Algeria", capital: "Algiers" },
    { country: "Andorra", capital: "Andorra la Vella" },
    { country: "Angola", capital: "Luanda" },
    { country: "Antigua and Barbuda", capital: "St. John's" },
    { country: "Argentina", capital: "Buenos Aires" },
    { country: "Armenia", capital: "Yerevan" },
    { country: "Australia", capital: "Canberra" },
    { country: "Austria", capital: "Vienna" },
    { country: "Azerbaijan", capital: "Baku" },
    { country: "Bahamas", capital: "Nassau" },
    { country: "Bahrain", capital: "Manama" },
    { country: "Bangladesh", capital: "Dhaka" },
    { country: "Barbados", capital: "Bridgetown" },
    { country: "Belarus", capital: "Minsk" },
    { country: "Belgium", capital: "Brussels" },
    { country: "Belize", capital: "Belmopan" },
    { country: "Benin", capital: "Porto-Novo" },
    { country: "Bhutan", capital: "Thimphu" },
    { country: "Bolivia", capital: "Sucre (constitutional) / La Paz (administrative)" },
    { country: "Bosnia and Herzegovina", capital: "Sarajevo" },
    { country: "Botswana", capital: "Gaborone" },
    { country: "Brazil", capital: "Brasília" },
    { country: "Brunei", capital: "Bandar Seri Begawan" },
    { country: "Bulgaria", capital: "Sofia" },
    { country: "Burkina Faso", capital: "Ouagadougou" },
    { country: "Burundi", capital: "Bujumbura" },
    { country: "Cabo Verde", capital: "Praia" },
    { country: "Cambodia", capital: "Phnom Penh" },
    { country: "Cameroon", capital: "Yaoundé" },
    { country: "Canada", capital: "Ottawa" },
    { country: "Central African Republic", capital: "Bangui" },
    { country: "Chad", capital: "N'Djamena" },
    { country: "Chile", capital: "Santiago" },
    { country: "China", capital: "Beijing" },
    { country: "Colombia", capital: "Bogotá" },
    { country: "Comoros", capital: "Moroni" },
    { country: "Congo (Congo-Brazzaville)", capital: "Brazzaville" },
    { country: "Costa Rica", capital: "San José" },
    { country: "Cote d'Ivoire", capital: "Yamoussoukro (official) / Abidjan (de facto)" },
    { country: "Croatia", capital: "Zagreb" },
    { country: "Cuba", capital: "Havana" },
    { country: "Cyprus", capital: "Nicosia" },
    { country: "Czechia (Czech Republic)", capital: "Prague" },
    { country: "Denmark", capital: "Copenhagen" },
    { country: "Djibouti", capital: "Djibouti" },
    { country: "Dominica", capital: "Roseau" },
    { country: "Dominican Republic", capital: "Santo Domingo" },
    { country: "Ecuador", capital: "Quito" },
    { country: "Egypt", capital: "Cairo" },
    { country: "El Salvador", capital: "San Salvador" },
    { country: "Equatorial Guinea", capital: "Malabo" },
    { country: "Eritrea", capital: "Asmara" },
    { country: "Estonia", capital: "Tallinn" },
    { country: "Eswatini (fmr. 'Swaziland')", capital: "Mbabane" },
    { country: "Ethiopia", capital: "Addis Ababa" },
    { country: "Fiji", capital: "Suva" },
    { country: "Finland", capital: "Helsinki" },
    { country: "France", capital: "Paris" },
    { country: "Gabon", capital: "Libreville" },
    { country: "Gambia", capital: "Banjul" },
    { country: "Georgia", capital: "Tbilisi" },
    { country: "Germany", capital: "Berlin" },
    { country: "Ghana", capital: "Accra" },
    { country: "Greece", capital: "Athens" },
    { country: "Grenada", capital: "St. George's" },
    { country: "Guatemala", capital: "Guatemala City" },
    { country: "Guinea", capital: "Conakry" },
    { country: "Guinea-Bissau", capital: "Bissau" },
    { country: "Guyana", capital: "Georgetown" },
    { country: "Haiti", capital: "Port-au-Prince" },
    { country: "Honduras", capital: "Tegucigalpa" },
    { country: "Hungary", capital: "Budapest" },
    { country: "Iceland", capital: "Reykjavik" },
    { country: "India", capital: "New Delhi" },
    { country: "Indonesia", capital: "Jakarta" },
    { country: "Iran", capital: "Tehran" },
    { country: "Iraq", capital: "Baghdad" },
    { country: "Ireland", capital: "Dublin" },
    { country: "Israel", capital: "Jerusalem" },
    { country: "Italy", capital: "Rome" },
    { country: "Jamaica", capital: "Kingston" },
    { country: "Japan", capital: "Tokyo" },
    { country: "Jordan", capital: "Amman" },
    { country: "Kazakhstan", capital: "Nur-Sultan" },
    { country: "Kenya", capital: "Nairobi" },
    { country: "Kiribati", capital: "South Tarawa" },
    { country: "Korea, North", capital: "Pyongyang" },
    { country: "Korea, South", capital: "Seoul" },
    { country: "Kosovo", capital: "Pristina" },
    { country: "Kuwait", capital: "Kuwait City" },
    { country: "Kyrgyzstan", capital: "Bishkek" },
    { country: "Laos", capital: "Vientiane" },
    { country: "Latvia", capital: "Riga" },
    { country: "Lebanon", capital: "Beirut" },
    { country: "Lesotho", capital: "Maseru" },
    { country: "Liberia", capital: "Monrovia" },
    { country: "Libya", capital: "Tripoli" },
    { country: "Liechtenstein", capital: "Vaduz" },
    { country: "Lithuania", capital: "Vilnius" },
    { country: "Luxembourg", capital: "Luxembourg" },
    { country: "Madagascar", capital: "Antananarivo" },
    { country: "Malawi", capital: "Lilongwe" },
    { country: "Malaysia", capital: "Kuala Lumpur" },
    { country: "Maldives", capital: "Malé" },
    { country: "Mali", capital: "Bamako" },
    { country: "Malta", capital: "Valletta" },
    { country: "Marshall Islands", capital: "Majuro" },
    { country: "Mauritania", capital: "Nouakchott" },
    { country: "Mauritius", capital: "Port Louis" },
    { country: "Mexico", capital: "Mexico City" },
    { country: "Micronesia", capital: "Palikir" },
    { country: "Moldova", capital: "Chisinau" },
    { country: "Monaco", capital: "Monaco" },
    { country: "Mongolia", capital: "Ulaanbaatar" },
    { country: "Montenegro", capital: "Podgorica" },
    { country: "Morocco", capital: "Rabat" },
    { country: "Mozambique", capital: "Maputo" },
    { country: "Myanmar (formerly Burma)", capital: "Naypyidaw" },
    { country: "Namibia", capital: "Windhoek" },
    { country: "Nauru", capital: "Yaren" },
    { country: "Nepal", capital: "Kathmandu" },
    { country: "Netherlands", capital: "Amsterdam" },
    { country: "New Zealand", capital: "Wellington" },
    { country: "Nicaragua", capital: "Managua" },
    { country: "Niger", capital: "Niamey" },
    { country: "Nigeria", capital: "Abuja" },
    { country: "North Macedonia", capital: "Skopje" },
    { country: "Norway", capital: "Oslo" },
    { country: "Oman", capital: "Muscat" },
    { country: "Pakistan", capital: "Islamabad" },
    { country: "Palau", capital: "Ngerulmud" },
    { country: "Panama", capital: "Panama City" },
    { country: "Papua New Guinea", capital: "Port Moresby" },
    { country: "Paraguay", capital: "Asunción" },
    { country: "Peru", capital: "Lima" },
    { country: "Philippines", capital: "Manila" },
    { country: "Poland", capital: "Warsaw" },
    { country: "Portugal", capital: "Lisbon" },
    { country: "Qatar", capital: "Doha" },
    { country: "Romania", capital: "Bucharest" },
    { country: "Russia", capital: "Moscow" },
    { country: "Rwanda", capital: "Kigali" },
    { country: "Saint Kitts and Nevis", capital: "Basseterre" },
    { country: "Saint Lucia", capital: "Castries" },
    { country: "Saint Vincent and the Grenadines", capital: "Kingstown" },
    { country: "Samoa", capital: "Apia" },
    { country: "San Marino", capital: "San Marino" },
    { country: "Sao Tome and Principe", capital: "São Tomé" },
    { country: "Saudi Arabia", capital: "Riyadh" },
    { country: "Senegal", capital: "Dakar" },
    { country: "Serbia", capital: "Belgrade" },
    { country: "Seychelles", capital: "Victoria" },
    { country: "Sierra Leone", capital: "Freetown" },
    { country: "Singapore", capital: "Singapore" },
    { country: "Slovakia", capital: "Bratislava" },
    { country: "Slovenia", capital: "Ljubljana" },
    { country: "Solomon Islands", capital: "Honiara" },
    { country: "Somalia", capital: "Mogadishu" },
    { country: "South Africa", capital: "Pretoria (administrative) / Cape Town (legislative) / Bloemfontein (judicial)" },
    { country: "South Sudan", capital: "Juba" },
    { country: "Spain", capital: "Madrid" },
    { country: "Sri Lanka", capital: "Colombo (commercial) / Sri Jayawardenepura Kotte (administrative)" },
    { country: "Sudan", capital: "Khartoum" },
    { country: "Suriname", capital: "Paramaribo" },
    { country: "Sweden", capital: "Stockholm" },
    { country: "Switzerland", capital: "Bern" },
    { country: "Syria", capital: "Damascus" },
    { country: "Taiwan", capital: "Taipei" },
    { country: "Tajikistan", capital: "Dushanbe" },
    { country: "Tanzania", capital: "Dodoma (official) / Dar es Salaam (administrative)" },
    { country: "Thailand", capital: "Bangkok" },
    { country: "Timor-Leste", capital: "Dili" },
    { country: "Togo", capital: "Lomé" },
    { country: "Tonga", capital: "Nukuʻalofa" },
    { country: "Trinidad and Tobago", capital: "Port of Spain" },
    { country: "Tunisia", capital: "Tunis" },
    { country: "Turkey", capital: "Ankara" },
    { country: "Turkmenistan", capital: "Ashgabat" },
    { country: "Tuvalu", capital: "Funafuti" },
    { country: "Uganda", capital: "Kampala" },
    { country: "Ukraine", capital: "Kyiv" },
    { country: "United Arab Emirates", capital: "Abu Dhabi" },
    { country: "United Kingdom", capital: "London" },
    { country: "United States of America", capital: "Washington, D.C." },
    { country: "Uruguay", capital: "Montevideo" },
    { country: "Uzbekistan", capital: "Tashkent" },
    { country: "Vanuatu", capital: "Port Vila" },
    { country: "Vatican City (Holy See)", capital: "Vatican City" },
    { country: "Venezuela", capital: "Caracas" },
    { country: "Vietnam", capital: "Hanoi" },
    { country: "Yemen", capital: "Sana'a" },
    { country: "Zambia", capital: "Lusaka" },
    { country: "Zimbabwe", capital: "Harare" },
  ];

  const universities = [
    "Joseph Ayodele Babalola University",
    "Harvard University",
    "Massachusetts Institute of Technology (MIT)",
    "Stanford University",
    "University of Oxford",
    "University of Cambridge",
    "California Institute of Technology (Caltech)",
    "University of Chicago",
    "Imperial College London",
    "Swiss Federal Institute of Technology (ETH Zurich)",
    "University of California, Berkeley",
    "Princeton University",
    "Yale University",
    "Columbia University",
    "University of Pennsylvania",
    "University of Michigan",
    "Johns Hopkins University",
    "University of Toronto",
    "University of Tokyo",
    "National University of Singapore (NUS)",
    "University of Melbourne",
    "Peking University",
    "Tsinghua University",
    "University of Hong Kong",
    "Seoul National University",
    "University of Sydney",
    "University of Copenhagen",
    "University of Amsterdam",
    "University of Munich",
    "University of Zurich",
    "University of Auckland",
    "University of Sao Paulo",
    "University of Cape Town",
    "University of Delhi",
    "McGill University",
    "University of British Columbia",
    "University of Paris (Sorbonne)",
    "University of Barcelona",
    "University of Milan",
    "University of Buenos Aires",
    "University of Mexico (UNAM)",
    "University of Nairobi",
    "University of Cairo",
    "University of Pretoria",
    "University of Auckland",
    "University of Wellington",
    "University of Lagos",
    "University of Ibadan",
    "Obafemi Awolowo University",
    "University of Benin",
    "Ahmadu Bello University",
    "University of Nigeria, Nsukka",
    "University of Ilorin",
    "Covenant University",
    "Federal University of Technology, Akure",
    "University of Port Harcourt",
    "University of Ghana",
    "University of Nairobi",
    "University of Cape Town",
    "University of Pretoria",
    "University of Dar es Salaam",
    "University of Johannesburg",
    "University of the Witwatersrand",
    "University of Kwazulu Natal",
    "Stellenbosch University",
    "Makerere University",
    "University of Nairobi",
    "University of Cape Town",
    "University of Pretoria",
    "University of Dar es Salaam",
    "University of Johannesburg",
    "University of the Witwatersrand",
    "University of Kwazulu Natal",
    "Stellenbosch University",
    "Makerere University",
    "University of Nairobi",
    "University of Cape Town",
    "University of Pretoria",
    "University of Dar es Salaam",
    "University of Johannesburg",
    "University of the Witwatersrand",
    "University of Kwazulu Natal",
    "Stellenbosch University",
    "Makerere University",
  ]

  const mySecret = `supersecret`;

  module.exports = {firstNames, lastNames, animalNames, universities, colors, countries}

  console.log (data.countries.country)